version: '3,2' # A versão do docker-compose que você deseja usar

services:
  app:
    image: nginx:latest # A imagem do contêiner a ser usada
    ports:
      - "80:81" # Mapeamento da porta do host para a porta do contêiner
