version: '3,2' # A versão do docker-compose que você deseja usar

services:
  web:
    image: nginx:latest # A imagem do contêiner a ser usada
    ports:
      - "80:80" # Mapeamento da porta do host para a porta do contêiner
    mode: replicated
    replicas: 2
